attributes:
  ol-domain_name:
    value: "domain.tld"
    label: "Domain name"
    weight: 10
    type: "text"
    regex:
      source: '\S'
      error: "Username field cannot be empty"
  ol-user_password:
    value: "very_strong_password"
    label: "OpneLDAP password"
    weight: 15
    type: "password"
    regex:
      source: '\S'
      error: "Password field cannot be empty"
  ol-ca_cert:
    value: "
      -----BEGIN CERTIFICATE-----
      MIIEATCCAumgAwIBAgIJAP0ZuasIHJlDMA0GCSqGSIb3DQEBBQUAMIGWMQswCQYD
      VQQGEwJSVTEPMA0GA1UECAwGTW9zY3dvMQ8wDQYDVQQHDAZNb3Njb3cxETAPBgNV
      BAoMCE1pcmFudGlzMREwDwYDVQQLDAhTZXJ2aWNlczEVMBMGA1UEAwwMKi5kb21h
      aW4udGxkMSgwJgYJKoZIhvcNAQkBFhlha2lyaWxvY2hraW5AbWlyYW50aXMuY29t
      MB4XDTE1MTAxNzA5MTYzM1oXDTE4MDgwNjA5MTYzM1owgZYxCzAJBgNVBAYTAlJV
      MQ8wDQYDVQQIDAZNb3Njd28xDzANBgNVBAcMBk1vc2NvdzERMA8GA1UECgwITWly
      YW50aXMxETAPBgNVBAsMCFNlcnZpY2VzMRUwEwYDVQQDDAwqLmRvbWFpbi50bGQx
      KDAmBgkqhkiG9w0BCQEWGWFraXJpbG9jaGtpbkBtaXJhbnRpcy5jb20wggEiMA0G
      CSqGSIb3DQEBAQUAA4IBDwAwggEKAoIBAQDSknBoUHmE0uAkU1KC7xLgSwIMxRnZ
      Po17tTuK3o8HnyYzEEpndJEF50yFZSfbRrAP9kA9826h8NUwN+eqkIhUKUgjbjPz
      OjGOEh6U7lPbbUf/cqH5i4vdiBMEpnIrhoJtxrjVgLxqpGEjWWHWk15R7cJ8wNgL
      /yeAOrrvq5Sro0GbL892oZuX0b/AW/77rGA00dUbKwIbB/bE2uJuWdRQGHykruW0
      Dc4FSRpeJLoNRGpZdJB3lpZZeV7W0JflVWd8gNa7f44lGb1nPl8HEMwU+ZZEw5Ik
      i0yrUAyo7LDsIlYeZiA8MQw2embNY9/DZDM0c9iGaye+iev//VY+/+rXAgMBAAGj
      UDBOMB0GA1UdDgQWBBQUtX2+bfaomb1FU1B4JkTpmDiAOjAfBgNVHSMEGDAWgBQU
      tX2+bfaomb1FU1B4JkTpmDiAOjAMBgNVHRMEBTADAQH/MA0GCSqGSIb3DQEBBQUA
      A4IBAQCk96ZT7m9NONA0CsIS0iiBQBG+53FHKoJ0/PdRE8Pv0qJGAX4HfyfUSDqP
      b+Flr6p1cFY4xfyeCgni8D4OKOYWhIPlShFENIEtyxRk6KezTwwjWdyiYAy6a58+
      XoNUOTcWe844JbO1GJmxDXirqxVRpP2oYHdWgsrVf49ym5mP6km+YtQpO0eu1232
      VmSIxB/465nGGQjTbm8cvpuap9u9rchDCcgHkkbByQ7sa7EpLkNbIhRsRzXlvqRQ
      sEzOXkMuzwEHNYtRPBlpUTX4fO6WOa6F8M+2Wvb0ZVWGoKuz3NCuUUN+tsjqsRme
      MheAPjNj7NZzlmtqGM6N/ZI3y6aK
      -----END CERTIFICATE-----"
    label: "CA cetificate"
    weight: 25
    description: "Copy CA certficate in pem format here."
    type: "textarea"
    regex:
      source: '\S'
      error: "Copy CA certficate in pem format here."
  ol-slapd_cert:
    value: "
      -----BEGIN CERTIFICATE-----
      MIIDqjCCApICCQD1hOKC2sg2qTANBgkqhkiG9w0BAQUFADCBljELMAkGA1UEBhMC
      UlUxDzANBgNVBAgMBk1vc2N3bzEPMA0GA1UEBwwGTW9zY293MREwDwYDVQQKDAhN
      aXJhbnRpczERMA8GA1UECwwIU2VydmljZXMxFTATBgNVBAMMDCouZG9tYWluLnRs
      ZDEoMCYGCSqGSIb3DQEJARYZYWtpcmlsb2Noa2luQG1pcmFudGlzLmNvbTAeFw0x
      NTEwMTcwOTE4NTVaFw0xNzAyMjgwOTE4NTVaMIGWMQswCQYDVQQGEwJSVTEPMA0G
      A1UECAwGTW9zY293MQ8wDQYDVQQHDAZNb3Njb3cxETAPBgNVBAoMCE1pcmFudGlz
      MREwDwYDVQQLDAhTZXJ2aWNlczEVMBMGA1UEAwwMKi5kb21haW4udGxkMSgwJgYJ
      KoZIhvcNAQkBFhlha2lyaWxvY2hraW5AbWlyYW50aXMuY29tMIIBIjANBgkqhkiG
      9w0BAQEFAAOCAQ8AMIIBCgKCAQEA8wS8stM0F0Fs8URr74ttYI28uuls9+h50WPr
      vTLCFoZEInnJeahVY2kE4a1DdfyP0Kkivfxamil8L38eHHhKJqBjiHMO4h02ZPXm
      ETPamQnHDQ/Xb8LYpw9rivf7AOcAaQTQnawjGTfcYOfM/LSszc8IrVnlwdQQ7qxh
      nZWd92VrlOGW1FIa3zs1aLZvs8wlle4y3gCa9jubee7A672mwdvfhwc/PgFSCSAQ
      aa/v9OPCFLLtKyJf58dAc0OP2sN0hVkBIK0ic4V9OVvgWHXbzWSLs44gqnCfO4yi
      i/Zvz3UKvsaqQ84E+AlCfdq9n1+E3sZ14fUzwvCzO97bHXOGkwIDAQABMA0GCSqG
      SIb3DQEBBQUAA4IBAQAQKIDM+OJog981hb5jzqNDMC0VLmcDHVTI7iRsiLD3mXzK
      R/EaOUk9spDEIzy8DEYnDBo9/8f6yy0mWi9mDNwn3o/9TT7mnDOnK8uhzfN2vdEL
      Fv5uatbjQmOiDhwBrJAgm+FJfNf+zpIWrdB7j7BDil9xyd/HJDx1owCIzgwJwe1W
      NvrhFtdA27rVvCNtFMPev3H8oX5QVw5gL4lqvjFJ/3mpJeRfxmi/PiaGgNnO1FFt
      0krG7kWp1FkcENyNJ1mayfzyu2ECCzgzm5s0LeAj1e+RiSRq9PvaW4s8EID4JmBn
      89U/gOmixvjiYvhR+gNj140hsOTzd7NpncHeMwtS
      -----END CERTIFICATE-----"
    label: "ldap server certificate"
    weight: 30
    description: "You can use generated cert for ldap server.(PLEASE USE PUBLIC IP assigned to master node as CommonName when creating csr)."
    type: "textarea"
    regex:
      source: '\S'
      error: "Copy ldap server certficate in pem format here."
  ol-slapd_key:
    value: "
      -----BEGIN RSA PRIVATE KEY-----
      MIIEpAIBAAKCAQEA0pJwaFB5hNLgJFNSgu8S4EsCDMUZ2T6Ne7U7it6PB58mMxBK
      Z3SRBedMhWUn20awD/ZAPfNuofDVMDfnqpCIVClII24z8zoxjhIelO5T221H/3Kh
      +YuL3YgTBKZyK4aCbca41YC8aqRhI1lh1pNeUe3CfMDYC/8ngDq676uUq6NBmy/P
      dqGbl9G/wFv++6xgNNHVGysCGwf2xNriblnUUBh8pK7ltA3OBUkaXiS6DURqWXSQ
      d5aWWXle1tCX5VVnfIDWu3+OJRm9Zz5fBxDMFPmWRMOSJItMq1AMqOyw7CJWHmYg
      PDEMNnpmzWPfw2QzNHPYhmsnvonr//1WPv/q1wIDAQABAoIBAQDEISWV467r6kZf
      T0SBNBDO3M5x+nvS/xJk8S8eb6GlJbU8xqWmqsoRR5jcfpWbBcIje+fmTAD10Q2g
      tdGP6sMwMKtCZPj6SW+ytmnJqhptPOJcqfb4KeQCWSXtpOKea9C8UuYB5sCYS7c2
      Z6BbbjPh96S48h3JPsUaCJnpdlUpb1nlgA59wJM8ew6bVrJgtYHbiCqEyy+T6YqT
      8DQ9tROTUmVOS3aG+1Zex+2rNNPDxRS5FSPGN2w3TyPkuBA4StndHDOv0B6LX/ZO
      i0BvUe0uXv5RtMT5RBuH7v531tNm0uRb5l27+31Wcd6C/t03k64QeXaPjPiEO5x3
      dSwWAlSBAoGBAP6pOtAEqkQw+vQIKBtYbOkR9jW8mK+XKLyHapx5atuo17cmk+jx
      SPO8fOP62xuLFLY1Zg5Xeqk1DR1BpNd58lOtAA+OZgXF6OUAKUSW3TSLcx3JpIRW
      QQxtm8/IwX6GN3ewcOmtozb0LFKCXKjKcV8//ANfwK1QaeR7dNDHphI3AoGBANOt
      3bsAq2MOX4KcaKyKpbm2jmWmXOQt3DKPH26jKBYABziV1LZHAm3j2dLhU7SZYhHO
      JHJkkpW5EmK7OdbHjfrKUbYkCJJDVU7PKrbVFBgaJQuDibeQTPcXjgN1ZY2U+JYM
      jIDE/CAV7d5j6sEmJ4EGgw8ypT56fO2g/oETExxhAoGBALwiCXDkAWWfScY+wGJz
      UQJeYqYQTjxqT433/KrciDT+515HAb51go+OEDXcfUI73XE+wcaWmeenaajTdhQ5
      4uwuQn07leNt8kA7fkFNst2+p6y56vBZSHUGBLXcehYe0Zt6nfAEdy+B87yA0jNg
      W6Eig+t6Mb3YSmKhUgtrcyTBAoGAAOoASh1voAbg3LSGMzCKFKo4JTI5tnaIO+Oo
      VBb6RlYLse/bsknONeFFAIcekGoVJVSJjcDnbSQWczyxvD6yW0HiZnHzY4ZM6QE2
      AwIaixwZytnvj05dNrfwUg2AucLJ7APz215+ZDkUBODTk6/xfbokeL1UP1fSEEig
      sLf/XiECgYBt0CafgqqwWj4hNyFsxXyZI6+hcm0yV38W9G7ugNGBd+LE7nWO8soU
      2XoS/Uzof03oeejBq9Dno+i3YNvPiFVzl9DMSzoVnDTHjYQOJ4oOnIDSfDvtTKjj
      Ky7WcY1BM46215s6pGgzIREtpz/BtuK/yXWGDUqhEno0Mv/5OXK0kQ==
      -----END RSA PRIVATE KEY-----"
    label: "ldap server key"
    weight: 30
    description: "You can use generated key for ldap server."
    type: "textarea"
    regex:
      source: '\S'
      error: "Copy ldap server key in pem format here."
  ol-first_cloud:
    type: "checkbox"
    weight: 35
    value: true
    label: "This is the first master"
    description: "if this is the first installation and or you plan to use single master - Please check. Otherwise uncheck it and specify IPs of remote masters below."
  ol-remote_master_fqdn:
    value: ""
    label: "Remote master servers"
    description: "If you have opeldap master servers deployed eralier with this plugin, please provide their fqdn here. Use comma as a delimiter."
    weight: 40
    type: "text"
    regex:
      source: '((([a-zA-Z0-9]|[a-zA-Z0-9][a-zA-Z0-9\-]*[a-zA-Z0-9])\.)*([A-Za-z0-9]|[A-Za-z0-9][A-Za-z0-9\-]*[A-Za-z0-9])(,\n|,?$)|^$)'
      error: "Specify valid FQDN"
