##############################################Custom Groups###################

- id: openldap-master
  type: group
  role: [openldap-master]
  required_for: [deploy_end]
  requires: [deploy_start]
  tasks: [hiera, globals, fuel_pkgs, hosts, tools, netconfig]
  parameters:
    strategy:
      type: one_by_one

##############################################Custom Tasks####################

- role: ['openldap-master']
  stage: post_deployment/6010
  type: puppet
  parameters:
    puppet_manifest: /etc/puppet/modules/osnailyfacter/modular/openldap/modules/openldap/manifests/openldap_master.pp
    puppet_modules: /etc/puppet/modules/osnailyfacter/modular/openldap/modules/:/etc/puppet/modules
    timeout: 720

- role: ['primary-controller', 'controller']
  stage: post_deployment/6020
  type: puppet
  parameters:
    puppet_manifest: /etc/puppet/modules/osnailyfacter/modular/openldap/modules/openldap/manifests/controller.pp
    puppet_modules: /etc/puppet/modules/osnailyfacter/modular/openldap/modules/:/etc/puppet/modules
    timeout: 720
