meta:
  conflicts:
  - compute
  - controller
  - cinder
  - cinder-vmware
  - ceph-osd
  - mongo
  - base-os
  description: Installs OpneLDAP master server.
  restrictions:
      - condition: "not (settings:openldap.metadata.enabled == true)"
  limits:
    max: 1
  name: openldap-master
name: openldap-master
volumes_roles_mapping:
- allocate_size: min
  id: os
