meta:
  conflicts:
  - compute
  - controller
  - cinder
  - cinder-vmware
  - ceph-osd
  - mongo
  - base-os
  description: Installs OpneLDAP master server.
  public_is_required: true
  restrictions:
    - condition: "not (settings:openldap.metadata.enabled == true)"
      action: hide
  name: openldap-master
name: openldap-master
volumes_roles_mapping:
- allocate_size: min
  id: os
